import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import NextLink from 'next/link'
import styles from '../../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>React - Block UI</title>
        <meta name="description" content="Generated by shanejix" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://github.com/block-org/block-ui">Block UI!</a>
        </h1>

        <p className={styles.description}>
          An open source design system for building modern websites and applications.
        </p>

        <div className={styles.grid}>
          <NextLink href="/en-us/guide/installation" passHref>
            <a className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Block UI features and API.</p>
            </a>
          </NextLink>

          <NextLink href="/en-us/components">
            <a className={styles.card}>
              <h2>Components &rarr;</h2>
              <p>Ever-increasing list of concise and aesthetic components.</p>
            </a>
          </NextLink>

          <NextLink href="/en-us/guide/themes">
            <a
              className={styles.card}
            >
              <h2>Customizable &rarr;</h2>
              <p>Configure sizes, colors, appearances, shapes, and more.</p>
            </a>
          </NextLink>

          <a
            href="https://github.com/block-org/block-ui"
            className={styles.card}
          >
            <h2>Open Sourced &rarr;</h2>
            <p>
              Block UI is open sourced and available free under MIT licence..
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
